web:
  image: jjbier/symfony
  container_name: nginx-server
  ports:
    - 8080:80
  volumes:
    - .:/var/www
  environment:
    NGINX_HOST: 'symfony.dev'
    NGINX_PORT: '80'
  tty: true

db:
  image: 'mysql:5.6.28'
  container_name: mysql-server
  command: mysqld --port 3386
  net: "host"
  volumes:
    - "/var/lib/mysql:/var/lib/mysql"
  environment:
    MYSQL_DATABASE: symfony
    MYSQL_USER: root
    MYSQL_ALLOW_EMPTY_PASSWORD: yes
  tty: true